### ISSUE TITLE
Material adjustments ...

### ISSUE THREAD

**Issue by davoodkharmanzar** [karasusan/OpenVDBForUnity#1]
thanks for this incredible plugin ...

is it possible to import and playing animated VDBs [or sequential]??
also is it possible to controlling animated VDBs by Timeline??
does this plugin be able to cast shadows to other objects??

and i can't to adjust their material directly!! seems that have to duplicate material properties to new and apply adjusted new material to VDB container ...
![capture](https://user-images.githubusercontent.com/10723167/44411080-9279f900-a51a-11e8-9c89-2eb4d4185580.JPG)

**Comment by karasusan** [comment]
I'm glad you like it.

Of course, I want to implement animated VDB and Timeline. 
I already have planned these features.

I implemented that generate the default material as `subasset`. That is why the material is locked.
I am sure of your complaints. I will consider another specification.

**Comment by karasusan** [comment]
Make Issue #4.

**Comment by karasusan** [comment]
Please check this PR.

https://github.com/karasusan/OpenVDBForUnity/issues/8

**Comment by karasusan** [comment]
Merged #8

**Comment by davoodkharmanzar** [comment]
i got these errors!!
![capture](https://user-images.githubusercontent.com/10723167/45694025-3a331880-bb13-11e8-9415-992f1ff6d606.JPG)

**Comment by karasusan** [comment]
Mm...
Maybe C# version is lower.

Check it.
https://docs.unity3d.com/Manual/ScriptingRuntimeUpgrade.html

Should I support lower C# version? 
This is not difficult for me.

**Comment by davoodkharmanzar** [comment]
i think lower is better ... because i'm using custom HDRP version of "Book of the Dead" :]

**Comment by davoodkharmanzar** [comment]
also i got these new errors after switching to .net 4.x and trying to extract VDB texture and material:
![capture](https://user-images.githubusercontent.com/10723167/45720421-15619400-bb59-11e8-8531-bf1e578dec73.JPG)

**Comment by karasusan** [comment]
Fixed #9

**Comment by karasusan** [comment]
> also i got these new errors after switching to .net 4.x and trying to extract VDB texture and material:
> ![capture](https://user-images.githubusercontent.com/10723167/45720421-15619400-bb59-11e8-8531-bf1e578dec73.JPG)

Oh, This problem specific to the Windows platform.
I'll check it on Windows.

**Comment by davoodkharmanzar** [comment]
seems that #10 is incompatible with .net 3.5!!

**Comment by karasusan** [comment]
#10 is a different matter than #9.

**Comment by karasusan** [comment]
Merged #9.
Now, running unittest for this plugin automatically on `Unity Cloud Build`.

**Comment by davoodkharmanzar** [comment]
well done 👍

**Comment by karasusan** [comment]
Merged #10.
